### ISSUE TITLE
Paired multi-modal data?

### ISSUE THREAD

**Issue by mayurmallya** [MedMNIST/MedMNIST#10]
Hi there,

Thanks for the wonderful dataset!

I was wondering if there are any paired images in this dataset. What I mean by paired images `(x_i, y_i)` is that they belong to 2 different modalities (in this case Modality X and Modality Y) and they come from the same patient and hence mapped to the same class labels.  

I see in the paper that OrganMNIST Axial, Coronal, and Sagittal come from the same source and have the same set of labels. I was wondering if these 3 modalities have paired images in them and if it includes the pairing data (which axial image is paired with which coronal and sagittal images).

Thank you.

**Comment by duducheng** [comment]
Hi @mayurmallya ,

Thank you for the interest ;)

Sorry to disappoint you. In MedMNIST, there is no multi-modal paired image, as it is not the primary focus of this study. 

I suggest that you may look for other academic datasets such as cardiac MRIs / brain MRIs (e.g., BRATS). The acs view of 3D volumes are not truly multi-modal.You could generate the views from any 3D datasets. e.g., LIDC or our own [RibFrac](https://ribfrac.grand-challenge.org/) dataset. In fact, we are also extending MedMNIST with 3D images, which may be released at June/July 2021. 

Good luck!
Jiancheng Yang
