### ISSUE TITLE
Normalization config

### ISSUE THREAD

**Issue by cliangyu** [MedMNIST/MedMNIST#11]
May I know if you have a normalization parameter setup for each sub-dataset? Thank you!

**Comment by duducheng** [comment]
Hi @DavidChenL ,

What do you mean the "normalization"? You can use your own parameters as you wish.

If you are talking about the benchmark ResNets, find it [here](https://github.com/MedMNIST/MedMNIST/blob/main/train.py#L54).

**Comment by DominickZhang** [comment]
> Hi @DavidChenL ,
> 
> What do you mean the "normalization"? You can use your own parameters as you wish.
> 
> If you are talking about the benchmark ResNets, find it [here](https://github.com/MedMNIST/MedMNIST/blob/main/train.py#L54).

Hi, the link is invalid now. Could you help provide a new one?

Many thanks!

**Comment by ThreeSRR** [comment]
Hi @DominickZhang ,

New link is [here](https://github.com/MedMNIST/experiments/blob/main/MedMNIST2D/train_and_eval_pytorch.py#L55).
