### ISSUE TITLE
separation of concern and publication on PyPI

### ISSUE THREAD

**Issue by psteinb** [MedMNIST/MedMNIST#12]
I just found this project by chance. I think it is a wonderful idea to have this many different modalities of data formatted like the MNIST dataset. This may give rise to a lot of opportunities during teaching or during sandboxing of methods.

I suggest to split off the `dataset.py` part completely and put this on PyPI. This way, any user doesn't have to rely on the dependencies which are exposed at this point. In addition, people can easily adopt the datasets by including a relevant statement in their `requirements.txt` or `environment.yml`.

What do you think?

**Comment by duducheng** [comment]
Hi @psteinb ,

Thanks for your interest!

> This may give rise to a lot of opportunities during teaching or during sandboxing of methods.

Yes, it is indeed how we are using MedMNIST now in our own research and machine learning course at SJTU ;-) This project was proposed to address our own pain points, and we are happy and active users of MedMNIST.  We are happy to know your use cases.

> I suggest to split off the dataset.py part completely and put this on PyPI. This way, any user doesn't have to rely on the dependencies which are exposed at this point.

Thanks for your great suggestion. Yes, the pure MedMNIST itself could depend on numpy only, even PyTorch / sklearn is not needed. I will try to make a minimal dependency of MedMNIST soon. As for PyPI, I have never made the package by myself, but it looks a very good idea, I will try it after I refactor the code. I do not want to make the packages installed from PyPI / GitHub different, so I need to think about how to clean it.

**Comment by psteinb** [comment]
Dear @duducheng - it's great to hear that my suggestions echo positively. In case you need a test dummy, please let me know. I tried something similar in the past (not sure it was as successfull as your tool https://github.com/psteinb/b3get).

We so far made good experience with tool called [poetry](https://python-poetry.org/),  that helps establish the workflow for publishing a project. The python world (in my mind) is consolidating the process of publishing packages considerably these days.

**Comment by duducheng** [comment]
Hi @psteinb ,

Thanks for your cool project. It seems to be something I could "copy" from ;) I will check it.

As for the package publishing, I don't have any idea yet since I have no experience with the standard tools =,= Anyway, I will check the poetry package as well.

BTW: We will soon release MedMNIST v2 (with 2 more 2D datasets + 6 3D datasets). One of them is also a bioimage dataset from BBBC.
