### ISSUE TITLE
the model sizes of the searched models and the search time by AutoKeras and Google AutoML Vision

### ISSUE THREAD

**Issue by pingguokiller** [MedMNIST/MedMNIST#13]
Sorry to be a bother. 

I am now following your paper. 
Some experimental results, i.e. the model sizes of the searched models and the search time by AutoKeras and Google AutoML Vision, may be useful to my paper.

Could you send me the records if it's possible?

Thank you very much!

my email: zhangjianwei@stu.scu.edu.cn

**Comment by duducheng** [comment]
Hi @pingguokiller ,

Thanks for your interest!

We are planning to release these model weights together with MedMNIST v2 recently. We are still cleaning the code repo and experiments, you will have them by the end of this month (or very soon).

Please stay tuned ;)

Cheers,
Jiancheng

**Comment by duducheng** [comment]
Hi @pingguokiller,

We have recently updated experiments code and trained model weights on [`MedMNIST/experiments`](https://github.com/MedMNIST/experiments). 

Feel free to check it out!

Jiancheng

**Comment by pingguokiller** [comment]
It's so nice of you.  Thanks for your help!发自我的华为手机-------- 原始邮件 --------发件人： Jiancheng ***@***.***>日期： 2021年8月23日周一 凌晨1:26收件人： MedMNIST/MedMNIST ***@***.***>抄送： pingguokiller ***@***.***>, Mention ***@***.***>主    题： Re: [MedMNIST/MedMNIST] the model sizes of the searched models and the search time by AutoKeras and Google AutoML Vision (#13)
Hi @pingguokiller,
We have recently updated experiments code and trained model weights on MedMNIST/experiments.
Feel free to check out!
Jiancheng
