### ISSUE TITLE
Can you provide the code for other models?

### ISSUE THREAD

**Issue by duxuan11** [MedMNIST/MedMNIST#14]
I am following your article, but you just provide the models of the baseline method in your GitHub.
So can you provide the code for other models? 
Such as auto-sklearn , AutoKeras and Google AutoML Vision.

**Comment by duducheng** [comment]
Hi @duxuan11 ,

We have recently updated experiments code and trained model weights on [`MedMNIST/experiments`](https://github.com/MedMNIST/experiments). 

Feel free to check it out!

Jiancheng
