### ISSUE TITLE
The temporal dimension of the 3D dataset

### ISSUE THREAD

**Issue by ariG23498** [MedMNIST/MedMNIST#17]
The 3D dataset have dimensions (N, 28, 28, 28) where N corresponds to the number of samples. I would just like to make myself clear on the point that `axis=1` stands for the temporal dimension here (number of frames of images).

I have also noticed in the following function, the frames are taken from `axis=1`
https://github.com/MedMNIST/MedMNIST/blob/9713611ce3e6aa879011f49d66d378af0462ef57/medmnist/utils.py#L39

Any help would be greately appreciated.
TIA!

**Comment by duducheng** [comment]
Hi @ariG23498 ,

Yes, the `axis=1` means the temporal dimension in videos, or the "axial dimension" of 3D images in medical image terminology.

Jiancheng

**Comment by ariG23498** [comment]
Thanks @duducheng 

Closing the issue.
