### ISSUE TITLE
Possible error in getting_started.ipynb?

### ISSUE THREAD

**Issue by qlero** [MedMNIST/MedMNIST#19]
Hello,

I was looking at the source code and attached notebooks in the folder `examples`. In the evaluation cell of the `getting_started.ipynb` notebook, we can find: 

```python
print('%s  acc: %.3f  auc:%.3f' % (split, *metrics)) 
```

This is shown as to have printed `train acc: 0.983  auc:0.834` when running the statement `test('train')`. However, looking at the `evaluator.py` file in `MedMNIST`, it seems that the evaluator object outputs the AUC first and then the accuracy. Consequently, the print statements in your notebook(s) may be switching the two metrics. 

Let me know if this is right.

Best regards,

qlero

**Comment by duducheng** [comment]
Hi @qlero ,

Thanks for figure it out!

I have quickly checked the code. It seems our mistake. We will fix it soon.

PS: our [experiment codebase](https://github.com/MedMNIST/experiments/blob/main/MedMNIST2D/train_and_eval_pytorch.py#L236) is correct. I suggest you to use that repo if you want to do more experiments. The notebook is only for quick exploration.

Jiancheng

**Comment by qlero** [comment]
Thank you very much. I'll refer to the experiment codebase if need be in the future. 
Best regards

Edit: misclicked the `comment with close` button

**Comment by ThreeSRR** [comment]
Hi @qlero ,

We have fixed the mistake. Thanks a lot!
