### ISSUE TITLE
Visualize 28x28x28 data

### ISSUE THREAD

**Issue by flyingdorothia** [MedMNIST/MedMNIST#20]
Dear repo,  

This is not a bug report. I try to visualize the 28x28x28 MNIST data, as the montage is not very clear.
Any example is available? Thanks,

**Comment by ThreeSRR** [comment]
Hi @lucyfan7266, 
You can use `save3d` in [`medmnist/utils.py`](https://github.com/MedMNIST/MedMNIST/blob/b724a369cdf6af1a88150a4a4f5eb9d9d953cd63/medmnist/utils.py)  to save the data as gif for visualization:  
 https://github.com/MedMNIST/MedMNIST/blob/b724a369cdf6af1a88150a4a4f5eb9d9d953cd63/medmnist/utils.py#L31

Or you can visualize the data frame by frame.
