### ISSUE TITLE
Not able to download dataset

### ISSUE THREAD

**Issue by meghbhalerao** [MedMNIST/MedMNIST#21]
Dear Authors,
Thank you for making the dataset public.
When I go to this link https://zenodo.org/record/5208230#.YluEcy-B0UE , and go to one of the datasets and click on download, nothing happens and the webpage simply hangs.
I also tried using the command line to download - 'python -m medmnist download' - and the download fails.
Thanks and please let me know at the earliest.
Megh

**Comment by meghbhalerao** [comment]
The links take long time to download when clicked directly and sometimes the portal times out. But the command line download still fails.

**Comment by ThreeSRR** [comment]
Hi, @meghbhalerao 

It seems that there was something wrong with zenodo. Now, the command line download works.

**Comment by meghbhalerao** [comment]
Thank you so much @ThreeSRR - The data is downloading now.
