### ISSUE TITLE
Links to download datasets are down 

### ISSUE THREAD

**Issue by kenza-bouzid** [MedMNIST/MedMNIST#22]
[The links ](https://zenodo.org/record/5208230#.Yl7L5oXMJaQ) to download medmnist datasets seem to be down. 
Download fails with the following error: meth_name = 'http_error_503', http_err = 1

**Comment by ThreeSRR** [comment]
Hi @kenza-bouzid,

We have uploaded the dataset in Google Drive, and you can download [here](https://drive.google.com/drive/folders/1nPTrxEbvqcQVSTSJSifgmJzkxEMWBJqr?usp=sharing).

**Comment by zoedsy** [comment]
Thank you for your contributions to the dataset, we appreciate it a lot. However, I find that from the 3dnodulemnist dataset downloaded from your link, in the last about 150 test images, they are all images with both max and min intensity 0. Maybe something is wrong with this. Would you please check it out?

**Comment by ThreeSRR** [comment]
Hi @zoedsy,

Thanks for figure it out! We have quickly checked our data and found the problem. We will fix it soon.

**Comment by ThreeSRR** [comment]
Hi @zoedsy,

We have fixed the mistake and updated the data. Thanks a lot!

**Comment by JOY-SWang** [comment]
the link https://drive.google.com/drive/folders/1nPTrxEbvqcQVSTSJSifgmJzkxEMWBJqr?usp=sharing is unavailable

**Comment by duducheng** [comment]
Hi @JOY-SWang ,

Please use the official Zenodo link. We no longer maintain the Google Drive version.

Jiancheng
