### ISSUE TITLE
Visualization of MedMNIST Images

### ISSUE THREAD

**Issue by meghbhalerao** [MedMNIST/MedMNIST#24]
Dear Authors,
Thank you again for making the dataset public. I have a question regarding the dermamnist dataset, and I am having some issues while visualizing it. I am using dermamnist with pytorch for a classification task, and my data loader is the following - 
```python
class MedMNISTDatasetProxy(Dataset):
    def __init__(self, tensors, transform=None):
        assert tensors[0].shape[0] == tensors[1].shape[0]
        self.tensors = tensors
        self.transform = transform

    def __getitem__(self, index):
        x = self.tensors[0][index]

        if self.transform:
            x = self.transform(x)

        y = torch.tensor(self.tensors[1][index])
        
        return x, y

    def __len__(self):
        return self.tensors[0].shape[0]
```
The transform list which I am passing is the following - 
```python
data_transform_proxy = transforms.Compose([transforms.ToTensor()])
```

I am making a data loader from this dataset (because I need that in my application), and I save the data loader and the load it again for the purpose of visualization. I am trying to visualize the images as follows, by using `transforms.ToPILImage()` in pytorch.
However when I visualize the images, I get a green shaded color for the dermamnist images, I'm not sure why this is happening. Following are a few of the image visualizations attached - 
![dermafullentropy_unnorm](https://user-images.githubusercontent.com/33202960/168456817-a750e4a8-64cc-46fb-b238-4ec1ff54c205.png)

The same issue happens with pathmnist also. The histopath images are usually pinkish color but the visualization, using the same procedure as above results in the following visualization - 
![pathfull_unnorm](https://user-images.githubusercontent.com/33202960/168456859-eba9b33b-26d3-4652-a7a5-46a82435fbd5.png)

If needed, my code for making the image grid is as follows - 
```python
def image_grid(imgs, rows, cols, original = False):
    print(rows, cols, len(imgs))
    assert len(imgs) == rows*cols

    w, h = imgs[0].size
    grid = Image.new('RGB', size=(cols*w, rows*h))

    grid_w, grid_h = grid.size
    
    for i, img in enumerate(imgs):
        if original:
            img = img.convert("RGB")
        grid.paste(img, box=(i%cols*w, i//cols*h))
    return grid
```
Thanks and please let me know if I am missing something.
Best Regards,
Megh

**Comment by meghbhalerao** [comment]
Additional info - I also tried various permutations of the color channels, RGB, BGR etc, 6 in total, but the images don't look similar to the one in the paper. I am using PIL to visualize the images after converting them from torch tensor. I might be missing some aspect of how to visualize the images, please do let me know and thanks for your time.

**Comment by duducheng** [comment]
I guess you can refer to our example code about how to visualize the dataset, which provides a successful implementation of `montage` with pillow. You can also check how PIL to torch tensor conversion works.
