### ISSUE TITLE
Query related to AUC and ACC score

### ISSUE THREAD

**Issue by Junaid199f** [MedMNIST/MedMNIST#27]
Dear Sir,
I noticed one thing that in your experimental results the AUC is greater than Accuracy score. Is it normal to have AUC score greater than Accuracy? Could you please explain this. Thanks

**Comment by duducheng** [comment]
Usually AUC is higher than ACC, no matter if it is binary or multiple classes. I suggest you check literature or do experiments to have a deeper understanding.
