### ISSUE TITLE
原图像1024*1024的，resize到28*28，医疗影像会不会丢失太多信息呢？

### ISSUE THREAD

**Issue by QianLingjun** [MedMNIST/MedMNIST#3]
hi，前辈，请问医学影像中，原图像1024*1024的，resize到28*28，用于病灶多类别分类任务，还有什么价值吗？细节信息不会丢失很多吗

**Comment by apache2046** [comment]
是啊是啊，28这分辨率低的发指啊

**Comment by duducheng** [comment]
很明显这个数据集并不是用来开发真实的医学图像应用的，正如MNIST一样，也是一个过于简化的数据。我们认为应该不会有人在MedMNIST上开发真实的医学图像应用，正如不会有人在MNIST开发真实的手写数据应用一样。

此数据集旨在提供一个有教育意义、标准化、丰富多样并且轻量化的数据集用来开发机器学习算法（如自动机器学习）。这些信息我们都在论文、项目主页等进行了充分的说明。可以看到即使是28这样的分辨率，其实模型仍然是可学习的，这使之足以承担我们希望其承担的目标。

如果需要原始分辨率的数据，可以参考我们的数据源，这些数据全部都是公开可获得的。

**Comment by apache2046** [comment]
既然你们已经辛苦整理了，能否也提供下高分的图像下载呢？只是训练研究，也许某些模型高分变率输入下效果会更好呢，多谢呀！
🙏

**Comment by QianLingjun** [comment]
都是公开数据，你可以查询到的，这个28*28的分辨率，确实太低了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MedMNIST/MedMNIST"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午3:06
收件人:&nbsp;"MedMNIST/MedMNIST"<MedMNIST@noreply.github.com&gt;;
抄送:&nbsp;"钱令军"<1763469890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MedMNIST/MedMNIST] 原图像1024*1024的，resize到28*28，医疗影像会不会丢失太多信息呢？ (#3)





 
既然你们已经辛苦整理了，能否也提供下高分的图像下载呢？只是训练研究，也许某些模型高分变率输入下效果会更好呢，多谢呀！
 🙏&nbsp;

**Comment by machanic** [comment]
请问原始的高分辨率的图片在哪里下载？

**Comment by duducheng** [comment]
我们论文中提供了原始数据的出处，若有需要可以自行获取。

**Comment by AIzealotwu** [comment]
> 既然你们已经辛苦整理了，能否也提供下高分的图像下载呢？只是训练研究，也许某些模型高分变率输入下效果会更好呢，多谢呀！ 🙏

你好，请问，一般的医学图像处理的分辨率设置到多少的经验值比较好？

**Comment by duducheng** [comment]
> > 既然你们已经辛苦整理了，能否也提供下高分的图像下载呢？只是训练研究，也许某些模型高分变率输入下效果会更好呢，多谢呀！ 🙏
> 
> 你好，请问，一般的医学图像处理的分辨率设置到多少的经验值比较好？

我们首页上更新了MedMNIST+（高分辨率版本）的相关信息，可以查看。至于分辨率的话，不同数据有差别，通常以你计算代价能接受的最大分辨率为准。最近有一个德国的团队（第三方）在MedMNIST+上进行了比较详尽的分析，可以了解下。https://github.com/MedMNIST/MedMNIST/issues/43
