### ISSUE TITLE
[feature request] the 3d dataset convert from npz to dicom

### ISSUE THREAD

**Issue by lmaxeniro** [MedMNIST/MedMNIST#31]
Hello,
Regarding converting the dataset from npz to another format: for 3d dataset, the  current implementation only provides the gif format:
```
assert postfix == "gif"
```
I would need to dicom format (dcm series data) -- do you have a plan to include that feature, or otherwise do you have suggestions about the ref. code that I can DIY?

**Comment by duducheng** [comment]
Hi @lmaxeniro ,

Thanks for the interests. We don’t have plan to do this as MedMNIST is not for clinical use. However, if you are interested in medical imaging formats, e.g., dicom or nifty, all these formats can be serialized easily from numpy array.

PRs are welcome!

Jiancheng

**Comment by lmaxeniro** [comment]
Thanks. BTW, is there some explanation about the npz file structure (for exp, how the test/train/val are allocated, and the label inforamtion etc..)? As this is a multiple sample data compressed binary file--I suppose the usual np.load() return can not be parsed directly to the usual np array.

**Comment by duducheng** [comment]
https://github.com/MedMNIST/MedMNIST#dataset

**Comment by duducheng** [comment]
The label information can found in https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/info.py

**Comment by lmaxeniro** [comment]
@duducheng One more question needs your help. I am able to read the numpy array and then convert it to a dcm file -- but from the gif file my understanding is that should be "a stack dcm image series", rather than one single dcm file for a "patient" -- is that correct? if that is true, how much dcm will be put together to get a stacked dicom image series?
