### ISSUE TITLE
running getting_started_without_PyTorch notebook report error

### ISSUE THREAD

**Issue by lmaxeniro** [MedMNIST/MedMNIST#32]
I meet such an error for running the getting_started_without_PyTorch notebook-- searched around this is Python version issue (I am using 3.11). check here: https://github.com/wireservice/agate/pull/737.
I downgrade the Python to 3.9.0 this error was gone.
Please consider upgrading the code.

```
File ~/prj/medmnist/MedMNIST/examples/dataset_without_pytorch.py:4
      2 import random
      3 import numpy as np
----> 4 from collections import Sequence
      5 from PIL import Image
      6 from medmnist.info import INFO, HOMEPAGE, DEFAULT_ROOT

ImportError: cannot import name 'Sequence' from 'collections' (/home/xlz/miniconda3/envs/medical/lib/python3.11/collections/__init__.py)
```

**Comment by duducheng** [comment]
Thank you for reporting this version compatibility issue. It has been fixed now.
