### ISSUE TITLE
Is it too small to process medical image data into a size of 28*28*28

### ISSUE THREAD

**Issue by Betty-J** [MedMNIST/MedMNIST#33]
Hi, thanks for sharing your work.
I have a question, is it too small to process 3D medical image data into a size of 282828, especially when classifying based on some detailed features in medical images?

How do you process medical images with an original size of such as 256*256*64 into a size of 28*28*28? Have you considered the loss of details caused by downsizing, I noticed that your work exhibits high performance metrics such as AUC.

**Comment by duducheng** [comment]
Processing from original size into 28 will absolutely lead to lost details. However, it’s not our emphasis. 

For 3D images, the original size is generally not that large because we use the VOIs. In terms of how, please refer to our paper.

Jiancheng

**Comment by Betty-J** [comment]
Thank you for your response. 

I didn't find a specific description of the processing method for 3D data in the paper. Regarding the dimensions of the sequence axis, if it cannot reach 28 or exceeds 28, there are several possible ways to handle it. For example, if you have a lung nodule and the sequence length in the depth size is 10, one approach is to resize or crop the volume to a size of 28 by using a bounding box that captures the region of interest. Alternatively, interpolation or zero-padding can be used. Regarding this point, could you explain it in detai, thanks a lot.

**Comment by duducheng** [comment]
In fact we’ve described it: “ …center-crop the spatially normalized images (with a spacing of 1 mm × 1 mm × 1 mm) into 28 × 28 × 28.”

there is no magic; what we do is cropping and resizing. If you would like to investigate the impact of resizing, I suggest to use the original version.

**Comment by Betty-J** [comment]
thanks again
