### ISSUE TITLE
License problem and use of this dataset?

### ISSUE THREAD

**Issue by Jumperkables** [MedMNIST/MedMNIST#34]
Hey,

I see that your README seems to explicitly state that the dataset is licensed under Creative Commons Attribution 4.0 International ([CC BY 4.0]), which allows for commercial use.

However, if I've understood your paper correctly, at least the DermaMNIST part of the dataset is derived from the HAM10000 dataset, which as I understand is explicitly licensed CC-BY-NC (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T&version=4.0&selectTab=termsTab)

If the DermaMNIST part of this dataset is indeed derived from HAM10000, and if this dataset is hosted under CC BY 4.0, then does this not constitute a license problem?

Looking forward to hearing back

Cheers,
Jumperkables

**Comment by duducheng** [comment]
Dear Jumperkables,

Thank you for bringing this licensing issue to our attention.

First and foremost, we'd like to acknowledge that we are not experts in licensing matters. It's possible that we might have made unintended oversights regarding the licensing of the MedMNIST dataset. The dataset was designed as a lightweight collection, and we did not fully consider the potential for commercial use.

We have previously been in contact with the authors of the HAM10000 dataset. During our communications, no concerns related to licensing were raised, which led us to believe that there weren't any issues in this regard.

We deeply respect the rights of original creators. Should the original authors or any relevant parties raise objections or concerns related to the license, we are more than willing to make appropriate modifications in response to their requests.

Cheers,
Jiancheng

**Comment by Jumperkables** [comment]
Hey Jiancheng,

Thanks for responding so quickly.
I'm no expert on licensing myself, I understand =)
If there is some mechanism to have different licenses for different subsections of datasets, perhaps that could be an option to consider
Would it be possible to update this issue with any changes to licensing you make?

Looking forward to hearing back

Cheers,
Jumperkables

**Comment by duducheng** [comment]
Hi Jumperkables,

Thanks for your suggestion. I've updated the license for DermaMNIST to CC BY-NC in the code, readme, website accordingly. 

If you find anything I forget, please let me know.

Jiancheng
