### ISSUE TITLE
Larger image options- 64*64 or 128*128?

### ISSUE THREAD

**Issue by Amritpal-001** [MedMNIST/MedMNIST#35]
I believe that intention of this work is to provide medical datasets for quick prototyping of ML algorithms. But since medical imaging classification generally relies on micro features and textures, 28*28 might be too small to learn anything meaningful.

I am curious if there is any way to access larger version of these datasets directly from your repo, say of size 64*64 or 128*128.

**Comment by zhaozh10** [comment]
I agree with that as well. Do you have plans to provide a dataset in the size of 224x224?

**Comment by mariamargherita** [comment]
Yeah that would be great, also because most CNNs for medical image classification are trained on 224x224 images :)

**Comment by duducheng** [comment]
Hi @Amritpal-001 , @zhaozh10 , @mariamargherita ,

Thank you for your comments! 

We are thrilled to release MedMNIST+ with larger sizes: 64x64, 128x128, and 224x224 for 2D, and 64x64x64 for 3D. As a complement to the previous 28-size MedMNIST, the large-size version could serve as a standardized benchmark for medical foundation models. 

The MedMNIST+ API (v3.0.0) is being tested, not yet on PyPI (latest version on PyPI is still v2.2.4). To preview, please install from Git:
        
    pip install --upgrade git+https://github.com/MedMNIST/MedMNIST.git

**Comment by duducheng** [comment]
Now you can install the new API using standard `pip install medmnist`.

**Comment by sdoerrich97** [comment]
Hi @Amritpal-001, @zhaozh10, @mariamargherita, @duducheng,

I'm thrilled to add that we have just released the first comprehensive baseline performance evaluation for MedMNIST+ covering all 12 2D datasets and all 4 available image resolutions!
For more details, check out this comment: https://github.com/MedMNIST/MedMNIST/issues/43#issuecomment-2107501874


Looking forward to your insights and feedback!

Cheers,
Sebastian

**Comment by duducheng** [comment]
Hi @sdoerrich97 ,

It’s really an exciting update! Thanks for your contribution to the MedMNIST community! I will add a reference to your work in the MedMNIST readme.

Jiancheng
