### ISSUE TITLE
Generation of OrganMNIST {Axial,Coronal,Sagittal}

### ISSUE THREAD

**Issue by zhaozh10** [MedMNIST/MedMNIST#36]
Hi, in the paper of MNIST_v1, you say that

> " We use bounding-box annotations of 11 body organs from another study [17] to obtain the organ labels. Hounsfield-Unit (HU) of the 3D images are transformed into grey scale with a abdominal window; we then crop 2D images from the center slices of the 3D bounding boxes in axial / coronal / sagittal views (planes)."

the I found that the size of OrganAMNIST is significantly larger than OrganMNIST3D. Does it mean that you crop multiple slices from a single 3D bbox for OrganAMNIST? I would appreciate it if you could provide further details regarding the generation of OrganaMNIST.

**Comment by duducheng** [comment]
Yes we cropped multiple slices in one bbox. I cannot recall all the details, but basically we do: select every 3 slices in 20-80% slices in each direction. The number here is just for illustration.

**Comment by zhaozh10** [comment]
Thanks for your timely response, it will help me push forward my project.
