### ISSUE TITLE
How to understand the label array

### ISSUE THREAD

**Issue by taokz** [MedMNIST/MedMNIST#37]
Hi thank you for your work and repo!

I would like to know the semantic meaning of the label array. For example, the chestmnist has the test label array (22433, 14), and the first label is array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8). What is the label it is associated with and how to convert the array to the corresponding label(s)? 

    "label": {
        "0": "atelectasis",
        "1": "cardiomegaly",
        "2": "effusion",
        "3": "infiltration",
        "4": "mass",
        "5": "nodule",
        "6": "pneumonia",
        "7": "pneumothorax",
        "8": "consolidation",
        "9": "edema",
        "10": "emphysema",
        "11": "fibrosis",
        "12": "pleural",
        "13": "hernia"
    },

I appreciate your help in advance. Thanks!

**Comment by duducheng** [comment]
Hello @taokz ,

Thanks for your interest! Sorry for a late reply.

To understand the label dict, you can find a description [here](https://github.com/MedMNIST/MedMNIST/tree/main#dataset).

Basically, the labels have different meanings according to the `task` tag. For instance, the ChestMNIST you show is `"task": "multi-label, binary-class"`, which means `0` for `normal` and `1` for `abnormal` for each class.

Jiancheng
