### ISSUE TITLE
How to use the latest 64, 128 and 224 version of dataset with data_flag without downloading externally?

### ISSUE THREAD

**Issue by balibata** [MedMNIST/MedMNIST#41]
Hi,

I appreciate it that you release the new version of this dataset and I want to make use of the larger ones like pathmnist_64.
My previous use of your data is as follows:
        data_flag = 'pathmnist'
        info = INFO[data_flag]
        channel = info['n_channels']
        im_size = (32, 32)
        num_classes = len(info['label'])

So for these new dataset like pathmnist_64, is there any new data_flag for me to use?

**Comment by duducheng** [comment]
Hi @balibata ,

***Update***: We are thrilled to release MedMNIST+ with larger sizes: 64x64, 128x128, and 224x224 for 2D, and 64x64x64 for 3D. As a complement to the previous 28-size MedMNIST, the large-size version could serve as a standardized benchmark for medical foundation models. 

The MedMNIST+ API (v3.0.0) is being tested, not yet on PyPI (latest version on PyPI is still v2.2.4). To preview, please install from Git:
        
    pip install --upgrade git+https://github.com/MedMNIST/MedMNIST.git

**Comment by balibata** [comment]
Thanks a lot!
