### ISSUE TITLE
Benchmark about Medmnist+

### ISSUE THREAD

**Issue by Weixiang-Sun** [MedMNIST/MedMNIST#43]
Can u release the benchmark of medmnist+ like the size 224*224?
best wish

**Comment by Weixiang-Sun** [comment]
https://zenodo.org/records/7782114
I find here, sry for disturb

**Comment by sdoerrich97** [comment]
Hey @Weixiang-Sun,

Exciting news! We've just rolled out the very first solid baseline performance evaluation for MedMNIST+, titled "Rethinking Model Prototyping through the MedMNIST+ Dataset Collection". This comprehensive evaluation covers **10 different deep learning models** trained via **3 distinct training schemes** across all **12 2D datasets** and available **image resolutions (28x28, 64x64, 128x128, and 224x224)** within the MedMNIST+ dataset.

You can check out the paper here: [Link to the paper](https://arxiv.org/abs/2404.15786)
And dive into the source code on our GitHub repository: [Link to the GitHub repository](https://github.com/sdoerrich97/rethinking-model-prototyping-MedMNISTPlus)

We're excited about how this evaluation can establish a baseline for future research in the MedMNIST+ benchmark domain. Looking forward to hearing your thoughts and contributions!

Cheers,
Sebastian

**Comment by duducheng** [comment]
Hi @sdoerrich97 ,

It’s really an exciting update! Thanks for your contribution to the MedMNIST community! I will add a reference to your work in the MedMNIST readme.

Jiancheng
