### ISSUE TITLE
How to visualise data without montage?

### ISSUE THREAD

**Issue by aymuos15** [MedMNIST/MedMNIST#44]
https://colab.research.google.com/drive/1Infsau44_tq-cdh3acQ1hCfW01Y-QkQy?usp=sharing

Given the `.montage()` makes PIL Images, why does using matplolib to visualise the images make it extremely blurry?

Can someone please let me know how to visualise the individual images?

**Comment by duducheng** [comment]
The image size in MedMNIST is only 28, so it should be of low-resolution, right ;)

If you would like to check higher resolution, use our latest API with 64, 128 and 224 size options. 

Jiancheng

**Comment by aymuos15** [comment]
Hmm, okay. I feel i was plotting it wrong. Makes sense when you plot in the same size as the image. Thanks :)
