### ISSUE TITLE
Easy way to combine datasets?

### ISSUE THREAD

**Issue by aymuos15** [MedMNIST/MedMNIST#45]
Is there any code snippet to combine multiple datasets?

Examples Organ(A/C/S)MNIST.

Ideally a 33-class problem instead 3 separate 11-class ones?

**Comment by duducheng** [comment]
Hi @aymuos15 ，

I'd suggest you implement your own dataloader, checking our dataset code as reference. 

Jiancheng

**Comment by aymuos15** [comment]
Alright! Thank you.
