### ISSUE TITLE
Labelling vs ground truth

### ISSUE THREAD

**Issue by rafaelblevin821** [MedMNIST/MedMNIST#48]
Hi, Just a quick question.

Where can I get confirmation of ground truth labels for your datasets? 

Specifically BreastMNIST and AdrenalMNIST3D.

**Comment by duducheng** [comment]
What do you mean by “confirmation”? Probably you can check the information in the info.py

**Comment by rafaelblevin821** [comment]
> What do you mean by “confirmation”? Probably you can check the information in the info.py

Thank you.
