### ISSUE TITLE
Where can I find sample IDs?

### ISSUE THREAD

**Issue by orenavram** [MedMNIST/MedMNIST#49]
Hi there, I was wondering how can I extract the IDs of a dataset's scans. For example, if I'd like to go back to the original scan (in the original dataset). I skimmed through the medmnist.dataset class (e.g. for ChestMNIST or NoduleMNIST3D) but it doesn't look like there's any relevant mention. Is the sample ID traceable? Thanks!

**Comment by ThreeSRR** [comment]
Hi @orenavram ,

We provide a CSV file for each MedMNIST subset [here](https://drive.google.com/drive/folders/1A_99qH_c-J0p_SatwSiaP_i1CvLUOzVo?usp=sharing), which maps the "image_id" in the subset to the corresponding image in the source dataset. For each entry, it details the specific "split" and "index" within the MedMNIST subset, along with the corresponding image name from the official source dataset.

**Comment by orenavram** [comment]
Thanks! This is very helpful!
