### ISSUE TITLE
What is the command line code to download one specific dataset?

### ISSUE THREAD

**Issue by aymuos15** [MedMNIST/MedMNIST#51]
`  python -m medmnist download pneumoniamnist --size=28 ` ends up throwing a root not found error but I remove that and do just   `python -m medmnist download --size=28` it seems to work?

**Comment by ThreeSRR** [comment]
Hi @aymuos15 ,

The command `python -m medmnist download --size=28` is used to download all datasets. Please refer to [here](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/__main__.py#L21) for the detailed implementation. 

To download a specific data, you can use the code directly, by setting `download=True`:
```
>>> from medmnist import PathMNIST
>>> train_dataset = PathMNIST(split="train", download=True)

**Comment by aymuos15** [comment]
Yes, I realized how obvious this was. Thank you :)
