### ISSUE TITLE
CHESTMNIST Dataset Shape

### ISSUE THREAD

**Issue by KarahanS** [MedMNIST/MedMNIST#53]
Hi,

The labels are in the format (# number of samples, 1) in all datasets (except CHESTMNIST), where a single number represents each label. However, in the CHESTMNIST dataset, the labels are in the format (# number of samples, 14), with each label being a one-hot vector. Could you explain the reason for this difference?

**Comment by duducheng** [comment]
The chest one is multi-label dataset, it means that each 0/1 as one of the 14 columns are for an existence of a disease. 

Jiancheng
