### ISSUE TITLE
pil_dataset is not used

### ISSUE THREAD

**Issue by wal-iston** [MedMNIST/MedMNIST#55]
Hi, I have some questions:
1. What is the role of pil_dataset? It's not used in the code.
2. Why is eval dataset not used?

Thanks.

**Comment by ThreeSRR** [comment]
The notebook [`getting_started.ipynb`](https://github.com/MedMNIST/MedMNIST/blob/main/examples/getting_started.ipynb) is ONLY intended for a quick exploration, i.e., it does not provide full training and evaluation functionalities. Indeed, `pil_dataset` is not used in this notebook, and we will remove it to avoid any ambiguity. 

For scripts with full training and evaluation functionalities, please refer to the [code](https://github.com/MedMNIST/experiments/blob/main/MedMNIST2D/train_and_eval_pytorch.py) in  [`MedMNIST/experiments`](https://github.com/MedMNIST/experiments), where the eval dataset is used.
