### ISSUE TITLE
transform not working?

### ISSUE THREAD

**Issue by wal-iston** [MedMNIST/MedMNIST#56]
Hi, I tried load data with transform.Normalize and it seems don't work. Can someone help me?

I tried:

transform = transforms.Compose([transforms.Normalize(mean=[.5,], std=[.5,])])
dataset = OrganSMNIST(split = 'test', transform=transform)

and values for dataset.imgs are the same as with no transform.

**Comment by ThreeSRR** [comment]
The variable `imgs` stores the data directly loaded from npz file, please refer to the code [here](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/dataset.py#L76). While the `transform` operation is performed when the `__getitem__` function is used to retrieve a sample ([here](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/dataset.py#L144)).

**Comment by wal-iston** [comment]
Thanks. I didn't know the transform operation works only when __getitem__ is used.
