### ISSUE TITLE
Create a custom class like PathMNIST with custom data.

### ISSUE THREAD

**Issue by wal-iston** [MedMNIST/MedMNIST#57]
Hi, I would like to create a class, like PathMNIST, such that it contain other data, for instance, the real MNIST.

Is it possible?

**Comment by ThreeSRR** [comment]
Certainly. You can modify the dataset class in [`dataset.py`](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/dataset.py) as you will.
