### ISSUE TITLE
Can't reproducde the results with the pretrained model you publish for PathMNIST 224

### ISSUE THREAD

**Issue by mkoohim** [MedMNIST/MedMNIST#58]
I tried the resnet50 pre-trained model (resnet50_224_1.pth) you shared for PathMNIST 224:
https://zenodo.org/records/7782114

But I can't reproduce the results you report:

train  auc: 0.91841  acc: 0.56873
val  auc: 0.91615  acc: 0.57147
test  auc: 0.81735  acc: 0.40418

These are the results I got. Any suggestions?

Thanks,

**Comment by ThreeSRR** [comment]
Hi @mkoohim ,

The results on images with 224 resolution in our paper (as well as the pre-trained model) are performed on 224 images resized from 28 directly, which is different from PathMNIST 224 in MedMNIST+.
