### ISSUE TITLE
Evaluator doesn't include size in file selection

### ISSUE THREAD

**Issue by owainkenwayucl** [MedMNIST/MedMNIST#59]
In doing some testing on different systems I ran across a bug - specifically, if you do not have the "orginal" size (28x28) version of a dataset downloaded, Evaluator for "larger" (e.g. 224x224) images fails with an error saying it is unable to load the .npz file for the 28x28 data.

```
Traceback (most recent call last):
  File "/home/uccaoke/Source/ML_Playground/MedMNIST/Gaudi/test_50.py", line 105, in <module>
    evaluator = medmnist.Evaluator(dataset, "test", size=224)
  File "/home/uccaoke/diffusers_runtime/lib/python3.10/site-packages/medmnist/evaluator.py", line 34, in __init__
    npz_file = np.load(os.path.join(self.root, "{}.npz".format(self.flag)))
  File "/home/uccaoke/diffusers_runtime/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/uccaoke/.medmnist/pathmnist.npz'
```

It looks like this is caused by: 

```python
         npz_file = np.load(os.path.join(self.root, "{}.npz".format(self.flag)))
```

https://github.com/MedMNIST/MedMNIST/blob/5c236af3309b8b2aea5bf9cecb270b57eb7bfff1/medmnist/evaluator.py#L34C1-L34C80

which does not include the `size`, or more specifically `self.size_flag`, in the filename it is loading.

(Ps - I'm happy to try and fix this and raise a PR if you prefer this!)

**Comment by ThreeSRR** [comment]
Hi @owainkenwayucl ,

Thanks for your bug report!

We have fixed this in [`Evaluator`](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/evaluator.py#L34).
