### ISSUE TITLE
about the input channel

### ISSUE THREAD

**Issue by sherrijj** [MedMNIST/MedMNIST#60]
你们好，我们想以medmnist及你们论文中的实验结果为benchmark，用于我们论文的实验对比，有一点想咨询一下，在论文中你们提到： The input channel is always 3 since we convert gray-scale images into RGB images. 但实际medmnist中的2D数据集并非都是3通道，并且在你们给出的code中，数据输入模型时是按照数据集图像的实际通道数，如1或者3，没有看到转换为3通道图像，所以想知道，你们论文中在每个数据集上的实验结果是按照该数据集图像的实际通道数，还是都转换成3通道的？希望得到你们的回复指点，我们才好严格按照相同的实验设置进行结果对比。谢谢！

**Comment by ThreeSRR** [comment]
你好，正如论文中所言，我们在跑实验的时候统一使用了三通道，对于灰度图像，我们使用Dataclass中的`as_rgb`参数将其转为RGB图像，具体的实现方式在[这里](https://github.com/MedMNIST/MedMNIST/blob/main/medmnist/dataset.py#L140)。

此外，我们同时提供了实验时的[训练代码和模型权重](https://github.com/MedMNIST/experiments/)，可以复现论文中的结果。

**Comment by sherrijj** [comment]
got it, thanks.
