### ISSUE TITLE
PyPi package needs update

### ISSUE THREAD

**Issue by BrannanKovachev** [MedMNIST/MedMNIST#62]
The PyPi package needs updating to match code at this repo.
Important changes to evaluator regarding image sizes aren't merged. In brief, the size_flag variable logic isn't incorporated in the public package.

**Comment by duducheng** [comment]
Hi @BrannanKovachev ,

Thanks for the bug report and I've updated the PyPI with the latest version. Feel free to try it out ;)

Jiancheng
