### ISSUE TITLE
Release of MedMNIST-Corrupted versions

### ISSUE THREAD

**Issue by francescodisalvo05** [MedMNIST/MedMNIST#63]
Dear @duducheng and the MedMNIST community,

thank you for all your great work on the MedMNIST+ codebase and datasets! 

In exploring model robustness, my colleagues and I have recently introduced a corrupted version of the 2D MedMNIST datasets, inspired by the ImageNet-C benchmark and tailored with modality-specific (test) image corruptions and associated augmentation APIs. 

We hope these corrupted datasets will benefit the community and extend MedMNIST's reach to those researchers and practitioners interested in evaluating and enhancing model robustness! 

For those interested, you can find the repository and the datasets [here](https://github.com/francescodisalvo05/medmnistc-api
). 

Additionally, we published the respective paper at the MICCAI (2024) Workshop on Advancing Data Solutions in Medical Imaging AI, and [here's](https://arxiv.org/abs/2406.17536)  the preprint. 

Looking forward to hearing your thoughts and contributions! 

Francesco

**Comment by duducheng** [comment]
Hi @francescodisalvo05 ,

Thank you for sharing this exciting update in creating the corrupted version! 

It’s a great contribution to the MedMNIST community. I’ll add a reference to your work in the MedMNIST README.

Happy holidays!

Best,
JC
