### ISSUE TITLE
getting_start.ipynb notebook scoring issue

### ISSUE THREAD

**Issue by impulsecorp** [MedMNIST/MedMNIST#7]
Your getting_start.ipynb is a great addition to the repo, but should it use train/val/test sets like your command line version does, where it picks the epoch with the highest val score as the best model, and then shows the test score for that model?

At the command line you do it like this:

==> Building and training model...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.39s/it]
epoch 0 is the best model
==> Testing model...
train AUC: 0.57632 ACC: 0.26923
val AUC: 0.49373 ACC: 0.26923
test AUC: 0.57728 ACC: 0.26923

**Comment by duducheng** [comment]
Hi, thanks for your interests!

The basic idea of the `getting_started.ipynb` is not the full training functionality; it is only intended for a quick exploration with the help of jupyter notebook, which is the reason why we only defined a simple CNN in it. Feel free to make your training notebook if needed. 

In fact, we are also working on a tutorial series using MedMNIST and jupyter notebooks, Stay tuned!

Jiancheng
